# Generated by Django 6.0.2 on 2026-02-27 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('shop_code', models.CharField(max_length=30, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('logo_emoji', models.CharField(default='🏪', max_length=10)),
                ('is_open', models.BooleanField(default=True)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('delivery_base_charge', models.FloatField(default=20.0)),
                ('delivery_per_km', models.FloatField(default=10.0)),
                ('delivery_base_km', models.FloatField(default=2.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('items_supplied', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('last_order_at', models.DateField(blank=True, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='shops.shop')),
            ],
        ),
    ]
