# Generated by Django 6.0.2 on 2026-02-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='delivery_radius_km',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='shop',
            name='offers_delivery',
            field=models.BooleanField(default=True),
        ),
    ]
