# Generated by Django 6.0.2 on 2026-02-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_loose',
            field=models.BooleanField(default=False, help_text='If checked, this item is sold by weight (price per kg).'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_stock_level',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.FloatField(default=0),
        ),
    ]
