# Generated by Django 6.0.2 on 2026-02-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_is_loose_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('dairy', 'Dairy & Eggs'), ('grains', 'Grains & Pulses'), ('snacks', 'Snacks & Biscuits'), ('beverages', 'Beverages'), ('spices', 'Spices & Masala'), ('oil', 'Oil & Ghee'), ('personal', 'Personal Care'), ('cleaning', 'Cleaning'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_loose',
            field=models.BooleanField(default=False, help_text='Sold by weight — price is per kg'),
        ),
    ]
