# Generated by Django 6.0.2 on 2026-03-05 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_category_alter_product_is_loose'),
        ('shops', '0002_shop_delivery_radius_km_shop_offers_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shops.shop'),
        ),
    ]
