# Generated by Django 6.0.2 on 2026-02-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_order_delivery_charge_order_distance_km_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='unit',
            field=models.CharField(default='pcs', max_length=10),
        ),
    ]
