# Generated by Django 6.0.2 on 2026-04-12 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_order_shop'),
        ('chatbot', '0006_add_order_status'),
    ]

    operations = [
    ]
