# Generated by Django 6.0.2 on 2026-04-13 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_merge_0005_order_shop_0006_add_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
