# Generated by Django 6.0.2 on 2026-04-13 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_remove_order_status'),
        ('chatbot', '0009_add_eta_note'),
    ]

    operations = [
    ]
