# Generated by Django 6.0.2 on 2026-04-13 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_merge_0008_remove_order_status_0009_add_eta_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='eta_note',
        ),
    ]
